spring:
  redis:
    database: 15
    host: localhost
    port: 6379
    password:
    timeout: 999
    jedis:
      pool:
        min-idle: 0
        max-idle: 0
        max-wait:

logging:
  file:
    path: /data/logs/firesword/
